# Generated by Django 5.2.3 on 2025-07-22 03:24

import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the property.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the property."),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the property.",
                        max_digits=10,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City where the property is located.", max_length=255
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Location of the property.", max_length=255
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        help_text="Image of the property.",
                        upload_to=properties.models.upload_property_image,
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        help_text="Optional second image of the property.",
                        null=True,
                        upload_to=properties.models.upload_property_image,
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        help_text="Optional third image of the property.",
                        null=True,
                        upload_to=properties.models.upload_property_image,
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        help_text="Optional fourth image of the property.",
                        null=True,
                        upload_to=properties.models.upload_property_image,
                    ),
                ),
                (
                    "image_5",
                    models.ImageField(
                        blank=True,
                        help_text="Optional fifth image of the property.",
                        null=True,
                        upload_to=properties.models.upload_property_image,
                    ),
                ),
                (
                    "image_6",
                    models.ImageField(
                        blank=True,
                        help_text="Optional sixth image of the property.",
                        null=True,
                        upload_to=properties.models.upload_property_image,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the property was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the property was last updated.",
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        help_text="The broker who is uploading the property.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
